/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <B_LED_aliases.h>
#include <B_LED.h>
#include <R_LED_aliases.h>
#include <R_LED.h>
#include <PWM_1.h>
#include <BuzzerPin_aliases.h>
#include <BuzzerPin.h>
#include <Clock_1.h>
#include <I2C_1.h>
#include <I2C_1_PVT.h>
#include <I2C_2.h>
#include <I2C_2_PVT.h>
#include <I2C_3.h>
#include <I2C_3_PVT.h>
#include <DATA1_aliases.h>
#include <DATA1.h>
#include <CLCK1_aliases.h>
#include <CLCK1.h>
#include <UART_1.h>
#include <DATA3_aliases.h>
#include <DATA3.h>
#include <CLCK3_aliases.h>
#include <CLCK3.h>
#include <Enable2_aliases.h>
#include <Enable2.h>
#include <CLCK2_aliases.h>
#include <CLCK2.h>
#include <DATA2_aliases.h>
#include <DATA2.h>
#include <isr_1.h>
#include <rts_aliases.h>
#include <rts.h>
#include <VDAC8_1.h>
#include <VDAC8_2.h>
#include <VDAC8_3.h>
#include <VDAC8_4.h>
#include <Pin_1_aliases.h>
#include <Pin_1.h>
#include <Pin_2_aliases.h>
#include <Pin_2.h>
#include <Pin_3_aliases.h>
#include <Pin_3.h>
#include <Pin_4_aliases.h>
#include <Pin_4.h>
#include <CW_CCW_1_aliases.h>
#include <CW_CCW_1.h>
#include <CW_CCW_2_aliases.h>
#include <CW_CCW_2.h>
#include <CW_CCW_3_aliases.h>
#include <CW_CCW_3.h>
#include <CW_CCW_4_aliases.h>
#include <CW_CCW_4.h>
#include <RUN_BRAKE_1_aliases.h>
#include <RUN_BRAKE_1.h>
#include <RUN_BRAKE_2_aliases.h>
#include <RUN_BRAKE_2.h>
#include <RUN_BRAKE_3_aliases.h>
#include <RUN_BRAKE_3.h>
#include <RUN_BRAKE_4_aliases.h>
#include <RUN_BRAKE_4.h>
#include <SPEED_1_aliases.h>
#include <SPEED_1.h>
#include <SPEED_2_aliases.h>
#include <SPEED_2.h>
#include <SPEED_3_aliases.h>
#include <SPEED_3.h>
#include <SPEED_4_aliases.h>
#include <SPEED_4.h>
#include <I2C_1_IntClock.h>
#include <I2C_2_IntClock.h>
#include <UART_1_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

