//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWM_v3_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWM_v3_0.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedTabDisplayName {
            get {
                return ResourceManager.GetString("AdvancedTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string BuiltInTabDisplayName {
            get {
                return ResourceManager.GetString("BuiltInTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMP Type 1:.
        /// </summary>
        internal static string CmpType1Label {
            get {
                return ResourceManager.GetString("CmpType1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment:.
        /// </summary>
        internal static string CmpType1LabelAlignment {
            get {
                return ResourceManager.GetString("CmpType1LabelAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompareType1 Equal not supported for Dead Band Mode..
        /// </summary>
        internal static string CompareType1NotSupportedForDeadBand {
            get {
                return ResourceManager.GetString("CompareType1NotSupportedForDeadBand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Value must be between {0} and {1}..
        /// </summary>
        internal static string CompareValueOutOfRange {
            get {
                return ResourceManager.GetString("CompareValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ConfigureTabDisplayName {
            get {
                return ResourceManager.GetString("ConfigureTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-3 Counts.
        /// </summary>
        internal static string DeadBandCountsItem {
            get {
                return ResourceManager.GetString("DeadBandCountsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Band Counts must be between {0} and {1}..
        /// </summary>
        internal static string DeadBandCountsOutOfRange {
            get {
                return ResourceManager.GetString("DeadBandCountsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string DeadBandDisabledItem {
            get {
                return ResourceManager.GetString("DeadBandDisabledItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Band Counts must be between {0} and {1} for Fixed Function implementation..
        /// </summary>
        internal static string DeadBandFFCountsOutOfRange {
            get {
                return ResourceManager.GetString("DeadBandFFCountsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dead Band mode not supported for CompareType1 set to Equal..
        /// </summary>
        internal static string DeadBandModeNotSupported {
            get {
                return ResourceManager.GetString("DeadBandModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in setting PWM Mode..
        /// </summary>
        internal static string ErrorSettingPWMMode {
            get {
                return ResourceManager.GetString("ErrorSettingPWMMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period = {0}{1}.
        /// </summary>
        internal static string FrequencyLabel {
            get {
                return ResourceManager.GetString("FrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component does not support Fixed Function implementation for PSoC 4 device. Please open config dialog and change implementation to UDB (by pressing &quot;Apply&quot; button)..
        /// </summary>
        internal static string ImplementationDrcError {
            get {
                return ResourceManager.GetString("ImplementationDrcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Time must be between {0} and {1}..
        /// </summary>
        internal static string KillTimeOutOfRange {
            get {
                return ResourceManager.GetString("KillTimeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period must be between {0} and {1}..
        /// </summary>
        internal static string PeriodOutOfRange {
            get {
                return ResourceManager.GetString("PeriodOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period = UNKNOWN SOURCE FREQ.
        /// </summary>
        internal static string UnknownFrequencyLabel {
            get {
                return ResourceManager.GetString("UnknownFrequencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not in a recognizable format..
        /// </summary>
        internal static string ValueNotInRecognizableFormat {
            get {
                return ResourceManager.GetString("ValueNotInRecognizableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is outside the range of UInt16 type..
        /// </summary>
        internal static string ValueOutOfUInt16Range {
            get {
                return ResourceManager.GetString("ValueOutOfUInt16Range", resourceCulture);
            }
        }
    }
}
