# THIS FILE IS AUTOMATICALLY GENERATED
# Project: E:\PSoc program\DskyTroostite1.0v\Design02\Design02.cydsn\Design02.cyprj
# Date: Fri, 06 Mar 2015 14:56:03 GMT
#set_units -time ns
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]


# Component constraints for E:\PSoc program\DskyTroostite1.0v\Design02\Design02.cydsn\TopDesign\TopDesign.cysch
# Project: E:\PSoc program\DskyTroostite1.0v\Design02\Design02.cydsn\Design02.cyprj
# Date: Fri, 06 Mar 2015 14:55:36 GMT
