//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPWM_P4_v1_0 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCPWM_P4_v1_0.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock freq: {0} {1}.
        /// </summary>
        public static string ClockDisplay {
            get {
                return ResourceManager.GetString("ClockDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock freq: UNKNOWN.
        /// </summary>
        public static string ClockUnknown {
            get {
                return ResourceManager.GetString("ClockUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare value could not be greater than Period value.
        /// </summary>
        public static string CompareValueError {
            get {
                return ResourceManager.GetString("CompareValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the initial value for the comparison registers and selects whether one or two comparison values are used..
        /// </summary>
        public static string HintCompare {
            get {
                return ResourceManager.GetString("HintCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects between compare and capture modes. In Compare mode the
        ///current count value is compared to the Compare Value to generate the cc
        ///output. Capture mode is used to capture the current counter value..
        /// </summary>
        public static string HintCompareCapture {
            get {
                return ResourceManager.GetString("HintCompareCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the counter direction.
        /// </summary>
        public static string HintCounterMode {
            get {
                return ResourceManager.GetString("HintCounterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode determines edge sensitivity of the signal.
        /// </summary>
        public static string HintMode {
            get {
                return ResourceManager.GetString("HintMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the initial value for the period registers and selects whether one or
        ///two period values are used.
        /// </summary>
        public static string HintPeriod {
            get {
                return ResourceManager.GetString("HintPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divides the TCPWM clock to create the counter clock.
        /// </summary>
        public static string HintPrescaler {
            get {
                return ResourceManager.GetString("HintPrescaler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present check box determines whether pin is on the symbol.
        /// </summary>
        public static string HintPresent {
            get {
                return ResourceManager.GetString("HintPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects between continuous and one shot mode.
        /// </summary>
        public static string HintRunMode {
            get {
                return ResourceManager.GetString("HintRunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync check box determines whether the input is synchronized.
        /// </summary>
        public static string HintSync {
            get {
                return ResourceManager.GetString("HintSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1}..
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        public static string TabBuiltIn {
            get {
                return ResourceManager.GetString("TabBuiltIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string TabNameConfig {
            get {
                return ResourceManager.GetString("TabNameConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM.
        /// </summary>
        public static string TabNamePWM {
            get {
                return ResourceManager.GetString("TabNamePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrature Decoder.
        /// </summary>
        public static string TabNameQuadDec {
            get {
                return ResourceManager.GetString("TabNameQuadDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer/Counter.
        /// </summary>
        public static string TabNameTC {
            get {
                return ResourceManager.GetString("TabNameTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCPWM.
        /// </summary>
        public static string TabNameTCPWM {
            get {
                return ResourceManager.GetString("TabNameTCPWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timer_down_mode {
            get {
                object obj = ResourceManager.GetObject("timer_down_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timer_up_down_mode0 {
            get {
                object obj = ResourceManager.GetObject("timer_up_down_mode0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timer_up_down_mode1 {
            get {
                object obj = ResourceManager.GetObject("timer_up_down_mode1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timer_up_mode {
            get {
                object obj = ResourceManager.GetObject("timer_up_mode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
